name: Merge test

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  merge_group:
    types: [checks_requested]

jobs:
  pre-job:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pre job
        run: |
          echo "Pre job"
        shell: bash

  echo-event-name:
    runs-on: ubuntu-latest
    needs: pre-job
    steps:
      - name: Echo event name
        run: |
          echo "Event name: ${{ github.event_name }}"
        shell: bash

